/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as CustomerLoginRouteImport } from './routes/customer.login'
import { Route as CustomerRegisterRouteImport } from './routes/customer.register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer/login',
  path: '/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRegisterRoute = CustomerRegisterRouteImport.update({
  id: '/customer/register',
  path: '/customer/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/services': typeof ServicesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/team': typeof AdminTeamRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/register': typeof CustomerRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/services': typeof ServicesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/team': typeof AdminTeamRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/register': typeof CustomerRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/services': typeof ServicesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/team': typeof AdminTeamRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/register': typeof CustomerRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/services'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/team'
    | '/customer/dashboard'
    | '/customer/login'
    | '/customer/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/services'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/team'
    | '/customer/dashboard'
    | '/customer/login'
    | '/customer/register'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/services'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/team'
    | '/customer/dashboard'
    | '/customer/login'
    | '/customer/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ServicesRoute: typeof ServicesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminTeamRoute: typeof AdminTeamRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerRegisterRoute: typeof CustomerRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/register': {
      id: '/customer/register'
      path: '/customer/register'
      fullPath: '/customer/register'
      preLoaderRoute: typeof CustomerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ServicesRoute: ServicesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminTeamRoute: AdminTeamRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerRegisterRoute: CustomerRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
